### ISSUE TITLE
there is no ftp clients that works with this server

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [waarp/WaarpFtp#37] opened 2016-05-24 11:32 UTC
hello, thank you for this server. I can't make it works with filezilla. For example when I do quick connection 
filezilla says: 

```
Status: Connecting to 127.0.0.1:2021...
Status: Connection established, waiting for welcome message...
Status: Insecure server, it does not support FTP over TLS.
Status: Server does not support non-ASCII characters.
Status: Logged in
Status: Retrieving directory listing...
Command:    PWD
Response:   257 "/test/test" is current directory
Command:    TYPE I
Response:   200 Type set to IMAGE NONPRINT
Command:    PASV
Response:   227 Entering Passive Mode (127,0,0,1,11,186)
Command:    MLSD
Response:   150 Opening IMAGE mode data connection
Error:  Could not read from transfer socket: ECONNRESET - Connection reset by peer
Response:   226 Transfer complete for MLSD /test/test
Error:  Failed to retrieve directory listing
Status: Starting upload of /tmp/fz3temp-1/empty_file_yq744zm
Status: Retrieving directory listing of "/test/test"...
Command:    PASV
Response:   227 Entering Passive Mode (127,0,0,1,11,187)
Command:    MLSD
Response:   150 Opening IMAGE mode data connection
Error:  Could not read from transfer socket: ECONNRESET - Connection reset by peer
Response:   226 Transfer complete for MLSD /test/test
Command:    SIZE 11
Response:   550 Not a file 11
Command:    PASV
Response:   227 Entering Passive Mode (127,0,0,1,11,188)
Command:    STOR 11
Response:   426 Transfer aborted for Unknown command
Error:  File transfer failed
```

Also I can't retreive file list from server even if the directory is not empty

```
Response:   226 Transfer complete for MLSD /test/test
Error:  Failed to retrieve directory listing
```

Also I can't make it working with firefox 46.0.1. Firefox says : The connection was reset

can you please help or give some hint what I did wrong ? I tried it on master brunch and wNetty41. If it is alfa, please fix version in pom file to 0.0.x.

**Comment by bcarlin** [comment] 2016-05-25 14:04
Hi Vitaly,

This bug was solved in 8a08605 on the branch wNetty41, which was later merged in master.
Are you using Waarp Gateway FTP ? or are you using the library WaarpFTP in a custom project ?

**Comment by vitaliy-kuzmich** [comment] 2016-05-25 14:33
Hi Bruno,
 I tried to run "WaarpFTP"  with SimpleGatewayFtpServer.java, but I could not connect to it. I was think it is simple FTP server... I run it on linux, I changed config.xml but the clients does not connect. Do you have working example?

**Comment by bcarlin** [comment] 2016-05-26 15:29
I see... I'm looking into it!

Cordialement,

Bruno Carlin
Waarp
01 56 38 51 08
07 64 07 84 87

2016-05-25 16:33 GMT+02:00 vitaliy-kuzmich <notifications@github.com>:

**Comment by vitaliy-kuzmich** [comment] 2016-06-01 08:36
excuse me but server version in pom.xml file does not fit to versioning standards, please read : https://en.wikipedia.org/wiki/Software_versioning. This server does not working as described in documentation http://waarp.github.io/WaarpFtp/project-info.html. Please fix server version to less then 1.

**Comment by fredericBregier** [comment] 2016-06-01 20:04
You can have support from os project but probably not having such comment. I believe you can learn a bit of gentleness, it can help sometimes.

Coming back to your issue, this project is not new (see the history on web site and commits). 
It might have right now an issue as you raising it, but it is a matter of a fix due to a regression issue, not because it is an "alpha" version.
We are looking at this issue to see the reason and fix it in the next version.

This server is in production for quite long now (2007). Our testing part might be not enough, but we still try to improve our quality.

Thank you for reporting this issue on the error, of course not on the version comment.

**Comment by vitaliy-kuzmich** [comment] 2016-06-01 20:47
I did expect that somebody would mention FTP client that is working with this server. I just tried to provide more details, at the previous message. I am sorry that I am very straightforward.

Yes I know that Waarp project is not new, I did read R66 docs and it is a great project, thank you for it.

**Comment by fredericBregier** [comment] 2016-06-01 21:30
Indeed, wa use this FTP server (either standalone or using WaarpGatewayFtp) with many FTP clients:

- Apache FTP client
- Filezilla client
- FTP command line (Linux, Windows)
- and various others

And in various modes:

- FTP
- FTPS implicit
- FTPS explicit
- all passive and active ways

So the reason we are glad you come back with this issue since we just missed it during the last release. It was working on previous one.

**Comment by bcarlin** [comment] 2016-06-03 09:19
There is indeed a bug that affects only `SimpleGatewayFtpServer`, but not WaarpGatewayFtp (I haven't tried `SimpleGatewaySslFtpServer` yet).
I'm trying to find out what and why

**Comment by vitaliy-kuzmich** [comment] 2016-06-03 09:43
I did quick look, it seems some standards changed, firefox and filezilla asks for file size before create it, so there is no file there and exception occures. Another bug is that it can't extract the list of the files.

**Comment by vitaliy-kuzmich** [comment] 2016-06-07 07:55
SimpleGatewaySslFtpServer does not work, it does not send welcome message. Also there are no errors in log.

**Closed** 2017-03-30 10:39 UTC
